# We don't run this due to GitHub's size limits

name: Push Container Image

on:
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and push images'
            run : |
              docker build . --tag ghcr.io/see2sound/see2sound:latest
              docker push ghcr.io/see2sound/see2sound:latest
